Kayla
BerganKDV/k-pay_file_uploader pull request #4
Opened 2020-12-22 21:30 UTC by kaykuhl

Changes are live on Azure

2021-01-05 18:40 UTC, kaykuhl commented
Updates 1/5/2021: 
Added logic to remove Submit Button after upload is complete / added Reset Button
Added error for document type that doesn't match
CSV File Generated for Errors / Added Button for Download
Errors that don't have a mapping file line associated like "Resume2.pdf has no match in the mapping file" will show up here as a line.  Errors that have a mapping file line will have that additional information (file_name, system_id, etc.) filled in for easier resubmittal after errors are fixed. 
Updated CSS
Updated Instructions
Added additional information and reorganization. 

2021-01-09 00:11 UTC, JonnyBoy333 requested changes

2021-01-09 00:11 UTC, JonnyBoy333 commented on .sdfcli.json
> +{
Did this file get added by mistake? I don't think there should be an SDF file in this project.

2021-01-09 00:11 UTC, JonnyBoy333 commented on package.json
> +        "dotenv": "^8.2.0",
Dotenv should be a dev dependency since it's not used on the production server

2021-01-09 00:41 UTC, JonnyBoy333 requested changes

2021-01-09 00:41 UTC, JonnyBoy333 commented on app.js
> +require('dotenv').config();
dotenv should only be required in the development environment. Historically I've used the preload option be adding to the node run command. You should also make sure you're environmental variables are added to the Application Settings in the Azure app.

2021-01-09 19:47 UTC, kaykuhl commented on .sdfcli.json
> +{
Yes, it was a mistake that it was added.

2021-01-11 19:37 UTC, kaykuhl commented
Moved dotenv to dev dependencies and using preload/Azure env for password variables. Pushed to production and authentication functionality still working.

2021-01-13 04:33 UTC, JonnyBoy333 approved these changes

2021-01-13 04:33 UTC, merged